name: locutus_dart
description: Dart wrapper for Locutus.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
